### ISSUE TITLE
parser-4-calcite-custom-tutorial编译过不了

### ISSUE THREAD

**Issue by weijunlu** [quxiucheng/apache-calcite-tutorial#15]
parser-4-calcite-custom-tutorial模块编译过不了
1. 执行mvn clean install
2. [INFO] apache-calcite-tutorial ............................ SUCCESS [  0.310 s]
[INFO] calcite-tutorial-0-translation ..................... SUCCESS [  0.387 s]
[INFO] calcite-tutorial-1-basic ........................... SUCCESS [  0.014 s]
[INFO] calcite-tutorial-2-parser .......................... SUCCESS [  0.002 s]
[INFO] parser-1-fmpp-tutorial ............................. SUCCESS [  0.407 s]
[INFO] parser-2-javacc-tutorial ........................... SUCCESS [  0.043 s]
[INFO] parser-3-calcite-tutorial .......................... SUCCESS [  0.443 s]
[INFO] parser-4-calcite-custom-tutorial ................... FAILURE [  2.458 s]
[INFO] calcite-tutorial-3-schema .......................... SKIPPED
[INFO] calcite-tutorial-4-validator ....................... SKIPPED
[INFO] validator-1-calcite-validator ...................... SKIPPED
[INFO] calcite-tutorial-common ............................ SKIPPED
[INFO] calcite-tutorial-9-rule ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.168 s
[INFO] Finished at: 2022-08-11T20:09:33+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project parser-4-calcite-custom-tutorial: Compilation failure: Compilation failure:
[ERROR] /D:/work/calcite/apache-calcite-tutorial/calcite-tutorial-2-parser/parser-4-calcite-custom-tutorial/target/generated-sources/com/github/quxiucheng/calcite/parser/tutorial/CustomSqlParserImpl.java:[107,8] com.github.quxiucheng.calcite.parser.tutorial.CustomSqlParserImpl不是抽象的, 并且未覆盖org.apache.calcite.sql.parser.SqlAbstractParserImpl中的抽象方法switchTo(org.apache.calcite.sql.parser.SqlAbstractParserImpl.LexicalState)

**Comment by YaoJian001** [comment]
这个问题后面你们解决了不

**Comment by quxiucheng** [comment]
修改编译报错了，运行包有一些问题，可以参考官网：https://github.com/apache/calcite/tree/calcite-1.26.0/server/src/main/codegen
