### ISSUE TITLE
想一起交流学习calcite

### ISSUE THREAD

**Issue by AstionMartionChan** [quxiucheng/apache-calcite-tutorial#2]
哥们，我最近想基于Flink1.8 SQL上扩展一些维表JOIN的功能，看了Flink SQL底层解析是通过Calcite的，然后发现哥们你的学习案例和笔记写的非常好和详细，所以想问你留个联系方式，想像您学习请教些Calcite相关的问题。

**Comment by quxiucheng** [comment]
可以给我发email,quxiuchengdev@gmail.com或者直接添加微信 qxc555

**Comment by AstionMartionChan** [comment]
> 可以给我发email,[quxiuchengdev@gmail.com](mailto:quxiuchengdev@gmail.com)或者直接添加微信 qxc555

太感谢了
