### ISSUE TITLE
底层查询的实现

### ISSUE THREAD

**Issue by schahaha** [quxiucheng/apache-calcite-tutorial#6]
有什么底层实现的案例吗？
从自定义Driver到底层sql逻辑的翻译？
我把parse vaildate 等都实现了，但是卡在了FilterableTable 和TranslatableTable这两个接口上。sql的翻译没看懂。

**Comment by quxiucheng** [comment]
其实这两个接口就是读取表，实现了读取表操作就好，官网源码中有example包中有示例，可以仿照那个写，他有一个读取csv的示例


schahaha <notifications@github.com> 于2020年9月8日周二 下午2:37写道：
